channels:
- conda-forge
dependencies:
- _go_select=2.3.0
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- altgraph=0.17.5
- anyio=4.12.1
- backports=1.0
- backports.tarfile=1.2.0
- backports.zstd=1.3.0
- brotli-python=1.2.0
- bzip2=1.0.8
- c-ares=1.34.6
- ca-certificates=2026.1.4
- cachecontrol=0.14.3
- cachecontrol-with-filecache=0.14.3
- certifi=2026.1.4
- cffi=2.0.0
- charset-normalizer=3.4.4
- cleo=2.1.0
- colorama=0.4.6
- crashtest=0.4.1
- cryptography=46.0.3
- dbus=1.13.6
- distlib=0.4.0
- dulwich=0.22.8
- exceptiongroup=1.3.1
- expat=2.7.3
- filelock=3.20.3
- findpython=0.6.3
- git=2.46.0
- go=1.23.6
- h11=0.16.0
- h2=4.3.0
- hpack=4.1.0
- httpcore=1.0.9
- httpx=0.28.1
- hyperframe=6.1.0
- icu=75.1
- idna=3.11
- importlib-metadata=8.7.0
- importlib_resources=6.5.2
- iniconfig=2.3.0
- invoke=2.2.0
- jaraco.classes=3.4.0
- jaraco.context=6.1.0
- jaraco.functools=4.4.0
- jeepney=0.9.0
- keyring=25.7.0
- keyutils=1.6.3
- krb5=1.21.3
- ld_impl_linux-64=2.45
- libblas=3.11.0
- libcblas=3.11.0
- libcurl=8.18.0
- libedit=3.1.20250104
- libev=4.33
- libexpat=2.7.3
- libffi=3.5.2
- libgcc=15.2.0
- libgcc-ng=15.2.0
- libgfortran=15.2.0
- libgfortran5=15.2.0
- libglib=2.84.0
- libgomp=15.2.0
- libiconv=1.18
- liblapack=3.11.0
- liblzma=5.8.2
- libnghttp2=1.67.0
- libnsl=2.0.1
- libopenblas=0.3.30
- libsqlite=3.51.2
- libssh2=1.11.1
- libstdcxx=15.2.0
- libstdcxx-ng=15.2.0
- libuuid=2.41.3
- libuv=1.51.0
- libxcrypt=4.4.36
- libzlib=1.3.1
- more-itertools=10.8.0
- msgpack-python=1.1.2
- mypy=1.14.1
- mypy_extensions=1.1.0
- ncurses=6.5
- nodejs=20.18.0
- numpy=2.4.1
- openssl=3.6.0
- packaging=25.0
- pbs-installer=2025.12.17
- pcre2=10.44
- perl=5.32.1
- pip=25.0.1
- pkginfo=1.12.1.2
- platformdirs=4.5.1
- pluggy=1.6.0
- poetry=2.1.1
- poetry-core=2.1.1
- psutil=7.2.1
- pycparser=2.22
- pyinstaller=6.16.0
- pyinstaller-hooks-contrib=2025.11
- pyproject_hooks=1.2.0
- pysocks=1.7.1
- pytest=8.3.4
- python=3.12.12
- python-build=1.4.0
- python-fastjsonschema=2.21.2
- python-installer=0.7.0
- python_abi=3.12
- rapidfuzz=3.14.3
- readline=8.3
- requests=2.32.5
- requests-toolbelt=1.0.0
- ruff=0.8.6
- secretstorage=3.4.1
- semver=3.0.2
- setuptools=80.9.0
- shellingham=1.5.4
- sniffio=1.3.1
- tk=8.6.13
- tomli=2.4.0
- tomlkit=0.12.4
- trove-classifiers=2026.1.14.14
- typing_extensions=4.15.0
- tzdata=2025c
- urllib3=2.6.3
- uv=0.9.26
- virtualenv=20.36.1
- wheel=0.45.1
- zipp=3.23.0
- zlib=1.3.1
- zstandard=0.25.0
- zstd=1.5.7
- pip:
  - actions-work-items==0.2.0
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.13.3
  - aiosignal==1.4.0
  - annotated-doc==0.0.4
  - annotated-types==0.7.0
  - astroid==2.15.8
  - attrs==25.4.0
  - Brotli==1.2.0
  - build==1.4.0
  - click==8.3.1
  - dill==0.4.0
  - docstring_parser_fork==0.0.5
  - execnet==2.1.2
  - fastapi-slim==0.121.3
  - fastjsonschema==2.21.2
  - frozenlist==1.8.0
  - httpx-sse==0.4.3
  - importlib_metadata==8.7.0
  - installer==0.7.0
  - isort==5.13.2
  - jsonschema==4.26.0
  - jsonschema-specifications==2024.10.1
  - lazy-object-proxy==1.12.0
  - lazydocs==0.5.0
  - markdown-it-py==4.0.0
  - mccabe==0.7.0
  - mcp==1.25.0
  - mdformat==1.0.0
  - mdformat-gfm==1.0.0
  - mdit-py-plugins==0.5.0
  - mdurl==0.1.2
  - msgpack==1.1.2
  - msgspec==0.19.0
  - multidict==6.7.0
  - oauthlib==3.3.1
  - propcache==0.4.1
  - pydantic==2.12.5
  - pydantic-settings==2.12.0
  - pydantic_core==2.41.5
  - pydocstyle==0.0.0.dev0
  - Pygments==2.19.2
  - PyJWT==2.10.1
  - pylint==2.17.7
  - pytest-datadir==1.8.0
  - pytest-regressions==1.0.6
  - pytest-xdist==3.8.0
  - python-dotenv==1.2.1
  - python-multipart==0.0.21
  - PyYAML==6.0.3
  - referencing==0.37.0
  - requests-oauthlib==2.0.0
  - rich==14.2.0
  - robocorp-log==3.0.1
  - robocorp-truststore==0.9.1
  - rpds-py==0.30.0
  - sema4ai-action-server==3.0.0
  - sema4ai-actions==1.6.6
  - sema4ai-build-common==0.0.3
  - sema4ai-common==0.3.0
  - sema4ai-devutils==0.0.1
  - sema4ai-http-helper==2.1.2
  - six==1.17.0
  - snowballstemmer==3.0.1
  - sse-starlette==3.2.0
  - starlette==0.50.0
  - termcolor==3.3.0
  - truststore==0.9.2
  - typer==0.21.1
  - types-invoke==2.0.0.10
  - types-PyYAML==6.0.12.20250915
  - typing-inspection==0.4.2
  - uvicorn==0.38.0
  - watchfiles==1.1.1
  - wcwidth==0.2.14
  - websockets==15.0.1
  - wrapt==1.17.3
  - yarl==1.22.0
